#!/usr/bin/env ansible-playbook -i inventory.ini --skip-tags=consul
---
# - hosts: bramble
#   gather_facts: true
#   remote_user: pi
#   become: yes
#   become_user: root
#   roles:
#     - utils
#     - { role: dnsmasq, consul_dns_domain: bramble.local }
#   tags:
#     - bramble

- name: setup the consul servers
  hosts: consul
  gather_facts: true
  remote_user: pi
  roles:
    - { role: consul, consul_is_server: yes }
  tags:
    - consul
    - consul-servers

- name: setup the baron
  hosts: baron
  gather_facts: true
  remote_user: pi
  roles:
    - { role: vault, vault_datacenter: alpha }
    # - { role: nomad, nomad_is_server: yes }
    # - prometheus
    # - grafana
  tags:
    - baron
    - vault
    - prometheus
    - grafana

- hosts: followers
  gather_facts: true
  remote_user: pi
  roles:
    - consul
    - nomad
  tags:
    - consul
    - followers
