#!/usr/bin/env ansible-playbook -i inventory.ini
---
- hosts: bramble
  gather_facts: true
  remote_user: pi
  become: yes
  become_user: root
  roles:
    - utils
    - { role: dnsmasq, consul_dns_domain: bramble.local }
  tags:
    - bramble

- hosts: leaders
  gather_facts: true
  remote_user: pi
  roles:
    - { role: consul, consul_is_server: yes }
    # - vault
    # - statsd
    # - prometheus
  tags:
    - leaders

- hosts: followers
  gather_facts: true
  remote_user: pi
  roles:
    - consul
  tags:
    - followers
