#!/usr/bin/env ansible-playbook -i inventory.ini
---
- hosts: bramble
  gather_facts: true
  remote_user: pi
  become: yes
  become_user: root
  roles:
    - utils
    - { role: dnsmasq, consul_dns_domain: bramble.local }
  tags:
    - bramble

- name: setup the consul servers
  hosts: consul
  gather_facts: true
  remote_user: pi
  roles:
    - { role: consul, consul_is_server: yes }
  tags:
    - consul
    - consul-servers

# - name: setup the baron
#   hosts: consul
#   gather_facts: true
#   remote_user: pi
#   roles:
#     - vault
#     # - prometheus
#   tags:
#     - baron
#     - vault
#     - prometheus

- hosts: followers
  gather_facts: true
  remote_user: pi
  roles:
    - consul
  tags:
    - consul
    - followers
